### ISSUE TITLE
Function request "Keep the object turning" & "Buffer option"&“Object type”

### ISSUE THREAD

**Issue by 1405100494** [Theuntextured/AsyncConveyorPlugin#11]
Hi!

1. I do not want to change the direction of goods at the corner when I need it. I hope this function can be added.

2. Is it possible to add a slow motion type to the conveying animation? Just like the timeline, I want to make the movement of Z-axis forklift and lifting machine, and the slow motion type can make the animation more realistic.

3. The object on the conveyor belt can only be a static mesh body, can it support the blueprint? If we can support blueprints, we can expand more features.

Thanks for your hardwork!

**Comment by Theuntextured** [comment]
Hey! 
I read through all 3 of your questions but I don't really understand what you mean... Could you try explaining it in other words and possibly use examples?

Thanks!

**Comment by 1405100494** [comment]
I'm really sorry! I used translation software, and maybe some of the technical terms are not quite accurate.

1.  I want the objects on the conveyor belt to keep the world rotating, and currently at the 90 degree turn the objects change direction along the route. I want to keep a constant world rotation before and after the turn.
Your example is a square that might not look obvious. You can see it very well if you change it into an irregular shape.

2.  Slow motion refers to the slow in and slow out of the animation, perhaps the translation of "inching" is more accurate. The current animation is linear. Just like changing the keyframe type in the timeline, this feature is meant to make the action of devices such as forklifts better.
The function of this plug-in can be used not only on the conveyor belt, but also on other docking devices. Usually these movements are not linear.

3.  As far as I know, the default return node of the specified goods in the plug-in is the static Mesh, and I do not know whether other types can be added.
This may be for performance reasons, but if you can also use the blueprint Actor as a cargo, you can have more expansion possibilities, such as keeping the world rotating mentioned in 1 can be implemented directly in the blueprint. Of course, it may be possible to implement higher performance in plug-ins, but the support of blueprint Actor class allows users to have more custom extensions.

Thanks!

**Comment by Theuntextured** [comment]
1. I don't have the plugin in front of me but I'm pretty sure that the rotation of the items does not change relative to the world.

2. Before saying anything else, I will tell you that the conveyors are meant to stay stationary in the world, so having them on a vehicle will not be possible unfortunately.
Therefore, your forklift would not work if you want it to move around the world. HOWEVER, if you want it to be stationary for some reason, you can accelerate and slow down the item using a timeline controlling the speed of the conveyor.

3. Unfortunately, due to performance issues, this would not be possible with the current plugin. The purpose of the plugin is to have optimal performance without impacting performance too much. Having an actor for every item would mean worsening performance immensely.
If you want to carry custom data on the conveyors, (for example you want each item yo have durability, which should be stored on the conveyors), you can go into the [last section of the documentation.](https://github.com/Theuntextured/AsyncConveyorPlugin/wiki/Advanced:-FItem-Struct).
For this, you have to rebuild the plugin from source but there is nothing I can do about it unfortunately....

Let me know if you need anything else or if I can close the issue!

**Comment by 1405100494** [comment]
I see, but regarding the first question, the world direction of goods is changing and I would like an option to keep the world spinning.

https://github.com/Theuntextured/AsyncConveyorPlugin/assets/72635400/55a336ba-e012-4722-8d41-0679a6974f2c

**Comment by Theuntextured** [comment]
I actually don't know when I implemented that. I was pretty sure I never did. Guess that 2am development affected my thinking....

**Comment by Theuntextured** [comment]
Fixed. The plugin should receive an update in the following hours!
