### ISSUE TITLE
Spline and mesh only rendered at 0,0,0

### ISSUE THREAD

**Issue by morneblake** [Theuntextured/AsyncConveyorPlugin#13]
It seems like the mesh that should be on the conveyor is rendered at 0,0,0 on the map and not on the actual static mesh for the actor. When you enabled draw debug shapes, you can see the items on the conveyor, but the static mesh is spawned on 0,0,0.

I have tested this in different projects and on different scenes and see exactly the same issues.

**Comment by Theuntextured** [comment]
Hello! Could you send me a screenshot of the material of the mesh?

**Comment by morneblake** [comment]
I have tried it with and without materials. This used to work pre version 2.

![image](https://github.com/user-attachments/assets/38cb0925-68db-4439-962a-5ea49b6eda37)

You can see the object to the right, and here below you can see the spline and nodes for each conveyor, stack on top of each other

![image](https://github.com/user-attachments/assets/5a1f845d-2291-44c7-9502-b89e8ab1bb29)

**Comment by Theuntextured** [comment]
So... I can't see the images (they dont load) but I think I know the problem. Version 2 uses a new method to display the meshes that is way faster than the one in <v1.3

There is a material function to add to the materials of every item in order to make it compatible. All instructions are on the documentation.

If you have any further issue, let me know on discord (theuntextured) and I'll answer asap.

**Comment by morneblake** [comment]
That was the problem, i assumed (I know) that if I didn't assign material then it would be okay. It wasn't

Adding the extra material function fixed the problem, thanks a million for the fast response <3

**Comment by Theuntextured** [comment]
No worries! Glad it works now!
